
export const LANGUAGES = [
  'English',
  'French',
  'Arabic',
  'Spanish',
  'Portuguese',
  'Swahili',
  'German',
  'Chinese',
  'Hindi',
  'Japanese',
  'Korean',
  'Thai',
  'Vietnamese',
];

export const REGIONS = [
  'Global',
  'Africa',
  'Central Africa',
  'Eastern Africa',
  'North Africa',
  'Southern Africa',
  'Western Africa',
  'Americas',
  'Southern America',
  'Asia',
  'Central Asia',
  'Europe',
  'Eastern Europe',
  'Northern Europe',
  'Southern Europe',
  'Western Europe',
];
