import type { User, Channel, Video } from './types';

export const users: User[] = [
  { id: '1', name: 'Admin User', email: 'admin@pocketnews.tv', avatar: 'https://picsum.photos/seed/user1/100/100', role: 'admin' },
  { id: '2', name: 'Jane Doe', email: 'jane.doe@example.com', avatar: 'https://picsum.photos/seed/user2/100/100', role: 'user' },
  { id: '3', name: 'John Smith', email: 'john.smith@example.com', avatar: 'https://picsum.photos/seed/user3/100/100', role: 'user' },
];

export const videos: Video[] = [
  {
    id: '1',
    youtubeId: 'dQw4w9WgXcQ',
    title: 'Exploring the Future of Renewable Energy',
    description: 'A deep dive into the innovations shaping the future of sustainable power.',
    views: 120543,
    watchTime: 25000,
    channelId: '1',
    createdAt: '2024-07-20T10:00:00Z',
    thumbnailUrl: 'https://i.ytimg.com/vi/h6fcK_fRYaI/hqdefault.jpg',
    contentCategory: 'Technology',
  },
  {
    id: '2',
    youtubeId: '3tmd-ClpJxA',
    title: 'Global Economic Outlook 2024',
    description: 'Experts analyze the trends and forecasts for the global economy.',
    views: 89765,
    watchTime: 15000,
    channelId: '2',
    createdAt: '2024-07-19T14:30:00Z',
    thumbnailUrl: 'https://i.ytimg.com/vi/3tmd-ClpJxA/hqdefault.jpg',
    contentCategory: 'Finance',
  },
  {
    id: '3',
    youtubeId: 'U_gANjtv28g',
    title: 'The Revolution of AI in Healthcare',
    description: 'How artificial intelligence is transforming patient care and medical research.',
    views: 215321,
    watchTime: 45000,
    channelId: '1',
    createdAt: '2024-07-18T09:00:00Z',
    thumbnailUrl: 'https://i.ytimg.com/vi/U_gANjtv28g/hqdefault.jpg',
    contentCategory: 'Technology',
  },
  {
    id: '4',
    youtubeId: 'VYOjWnS4cMY',
    title: 'Breaking Down the Latest Political Developments',
    description: 'A panel of journalists discusses the most recent events in global politics.',
    views: 54321,
    watchTime: 9000,
    channelId: '3',
    createdAt: '2024-07-17T18:00:00Z',
    thumbnailUrl: 'https://i.ytimg.com/vi/VYOjWnS4cMY/hqdefault.jpg',
    contentCategory: 'Politics',
  },
  {
    id: '5',
    youtubeId: 'Y8J-H_y2V5w',
    title: 'Inside the World of Venture Capital',
    description: 'An exclusive look into how venture capitalists decide which startups to fund.',
    views: 76543,
    watchTime: 12000,
    channelId: '2',
    createdAt: '2024-07-16T11:00:00Z',
    thumbnailUrl: 'https://i.ytimg.com/vi/Y8J-H_y2V5w/hqdefault.jpg',
    contentCategory: 'Finance',
  },
  {
    id: '6',
    youtubeId: '6Af6b_wy_KE',
    title: 'Cultural Movements Shaping Society',
    description: 'Exploring the art, ideas, and trends that are defining the modern era.',
    views: 43210,
    watchTime: 7000,
    channelId: '4',
    createdAt: '2024-07-15T16:45:00Z',
    thumbnailUrl: 'https://i.ytimg.com/vi/6Af6b_wy_KE/hqdefault.jpg',
    contentCategory: 'Culture',
  },
   {
    id: '7',
    youtubeId: 'i_LwzRVP7bg',
    title: 'The Quantum Computing Race',
    description: 'Who will win the race to build a quantum computer? A look at the key players.',
    views: 180123,
    watchTime: 32000,
    channelId: '1',
    createdAt: '2024-07-14T10:00:00Z',
    thumbnailUrl: 'https://i.ytimg.com/vi/i_LwzRVP7bg/hqdefault.jpg',
    contentCategory: 'Technology',
  },
  {
    id: '8',
    youtubeId: 'fis26HvvD5A',
    title: 'Election 2024: Key Issues and Debates',
    description: 'A comprehensive overview of the major topics in the upcoming election cycle.',
    views: 95432,
    watchTime: 18000,
    channelId: '3',
    createdAt: '2024-07-13T13:00:00Z',
    thumbnailUrl: 'https://i.ytimg.com/vi/fis26HvvD5A/hqdefault.jpg',
    contentCategory: 'Politics',
  },
];

export const channels: Channel[] = [
  {
    id: '1',
    name: 'Tech Forward',
    description: 'The future of technology, science, and innovation.',
    videoIds: ['1', '3', '7'],
  },
  {
    id: '2',
    name: 'Market Movers',
    description: 'Insights into finance, business, and the global economy.',
    videoIds: ['2', '5'],
  },
  {
    id: '3',
    name: 'The Political Arena',
    description: 'In-depth analysis of global politics and current events.',
    videoIds: ['4', '8'],
  },
  {
    id: '4',
    name: 'Culture Canvas',
    description: 'Exploring the world of arts, lifestyle, and modern culture.',
    videoIds: ['6'],
  },
];
