import Link from 'next/link';
import SiteHeader from '../../components/site-header';

export const metadata = {
  title: 'Terms & Conditions | PocketStream',
  description: 'Terms and conditions for using PocketStream — a free news and podcast streaming platform.',
};

export default function TermsPage() {
  const effectiveDate = 'May 1, 2026';

  return (
    <div className="flex min-h-screen w-full flex-col">
      <SiteHeader hideCategoryNav />
      <main className="flex-1 container mx-auto px-4 py-12 max-w-3xl">
        <h1 className="text-3xl font-bold mb-2">Terms &amp; Conditions</h1>
        <p className="text-sm text-muted-foreground mb-10">Effective date: {effectiveDate}</p>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-8">

          <section>
            <h2 className="text-xl font-semibold mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using PocketStream (&quot;Platform&quot;, &quot;we&quot;, &quot;our&quot;), you agree to be bound by
              these Terms &amp; Conditions and our{' '}
              <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>.
              If you do not agree, please do not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">2. Description of Service</h2>
            <p>
              PocketStream is a free content curation platform that aggregates publicly available news
              broadcasts and podcast episodes from verified creators and channels. The Platform provides
              centralized access to:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Live and recorded <strong>News videos</strong> sourced from YouTube and direct video uploads.</li>
              <li><strong>Podcast episodes</strong> — including audio podcasts, video podcasts, and live streams —
                published by creators on the Platform.</li>
              <li><strong>Shorts</strong> — short-form video news clips.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">3. Free Platform &amp; No Revenue Sharing</h2>
            <p>
              PocketStream is provided <strong>free of charge</strong> to all viewers. We do not currently
              monetize content through subscription fees, paywalls, or viewer payments.
            </p>
            <p className="mt-2">
              <strong>There is no revenue-sharing programme with creators at this time.</strong> Creators and
              channel owners who publish content on the Platform do so to reach the Platform audience
              and are not entitled to payment, royalties, or any share of advertising income generated by the
              Platform.
            </p>
            <p className="mt-2">
              We reserve the right to introduce revenue-sharing, monetisation, or paid tiers in the future.
              Any such changes will be announced with reasonable notice and updated in these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">4. Advertising</h2>
            <p>
              PocketStream may display advertisements on content across the Platform, including news videos,
              podcast episodes, and shorts. By publishing content on the Platform, creators acknowledge and
              accept that:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Advertisements may appear on or alongside their published content.</li>
              <li>All advertising revenue generated belongs exclusively to PocketStream.</li>
              <li>No portion of advertising revenue is shared with creators unless a separate written
                agreement is in place.</li>
            </ul>
            <p className="mt-2">
              <strong>Advertising opportunities:</strong> Businesses, brands, and individuals may contact us
              to place targeted advertisements alongside news and podcast content on the Platform. Advertising
              on PocketStream is a commercial service offered by us, separate from any creator or viewer
              account. To enquire about advertising, please contact us at{' '}
              <a href="mailto:ads@pocketnewstv.com" className="text-primary hover:underline">
                ads@pocketnewstv.com
              </a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">5. Creator Accounts</h2>
            <p>
              To publish content (news channels, podcast episodes, or shorts) you must apply for a Creator
              account and be approved by PocketStream. By submitting content you confirm that:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>You own or have the rights to distribute all submitted content.</li>
              <li>Your content does not infringe any third-party copyright, trademark, or other intellectual
                property rights.</li>
              <li>Your content complies with all applicable laws and our content guidelines.</li>
              <li>You grant PocketStream a non-exclusive, worldwide, royalty-free licence to host, display,
                stream, and promote your content on the Platform.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">6. Intellectual Property</h2>
            <p>
              All video content, logos, thumbnails, and trademarks displayed on the Platform belong to their
              respective owners and original channels. PocketStream does not claim ownership of third-party
              content. The PocketStream brand, logo, and original Platform code are owned exclusively by
              PocketStream.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">7. Prohibited Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Use the Platform for any unlawful purpose.</li>
              <li>Scrape, crawl, or extract Platform data without written permission.</li>
              <li>Upload or share content that is defamatory, hateful, obscene, or misleading.</li>
              <li>Attempt to disrupt or interfere with the Platform&apos;s infrastructure.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">8. Disclaimers &amp; Limitation of Liability</h2>
            <p>
              The Platform is provided &quot;as is&quot; without warranties of any kind. We do not guarantee
              uninterrupted access or the accuracy of curated content. To the maximum extent permitted by
              law, PocketStream is not liable for any indirect, incidental, or consequential damages arising
              from your use of the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">9. Changes to These Terms</h2>
            <p>
              We may update these Terms at any time. Continued use of the Platform after changes are posted
              constitutes acceptance of the revised Terms. We will update the effective date at the top of
              this page when changes are made.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">10. Contact</h2>
            <p>
              For questions about these Terms, please contact us at{' '}
              <a href="mailto:legal@pocketnewstv.com" className="text-primary hover:underline">
                legal@pocketnewstv.com
              </a>.
            </p>
          </section>

        </div>
      </main>
      <footer className="py-8 border-t border-border/40 text-center text-sm text-muted-foreground">
        <p>© {new Date().getFullYear()} PocketStream. All rights reserved.</p>
        <div className="flex justify-center gap-4 mt-2">
          <Link href="/terms" className="hover:text-foreground hover:underline">Terms &amp; Conditions</Link>
          <Link href="/privacy" className="hover:text-foreground hover:underline">Privacy Policy</Link>
        </div>
      </footer>
    </div>
  );
}
